# Generated by Django 3.2.5 on 2021-08-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_time',
            field=models.TimeField(),
        ),
    ]
